### ISSUE TITLE
Home assistant logs telling me to report this to the author of the integration

### ISSUE THREAD

**Issue by andreamag00** [smartHomeHub/SmartIR#1071]
Hi!
I've found the following alert in my home assistant logs, telling me to report it to the author of the integration.
Thank you very much.
Andrea

LOGS:

> Logger: homeassistant.helpers.entity
> Source: helpers/entity.py:565 
> First occurred: 25 giugno 2023, 20:15:26 (1 occurrences) 
> Last logged: 25 giugno 2023, 20:15:26
> 
> **Entity** climate.aria_condizionata_app_9_camera_ale_mansarda_controllo_manuale (**<class 'custom_components.smartir.climate.SmartIRClimate'>**) **is using self.async_update_ha_state(), without enabling force_update**. Instead **it should use self.async_write_ha_state()**, please **report it to the custom integration author**.
> 

MY SYSTEM:

> - home assistant 2023.6.3 on a raspberry pi4
> - SmartIR 1.17.7 -> I'm using it with broadlink rm4 mini + daikin AC (code 1116)

**Comment by tariya-garker** [comment]
+1
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:565
First occurred: 17:27:35 (2 occurrences)
Last logged: 17:27:35

Entity climate.mitsu (<class 'custom_components.smartir.climate.SmartIRClimate'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.
Entity climate.toshiba (<class 'custom_components.smartir.climate.SmartIRClimate'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.


Home Assistant 2023.6.0
Supervisor 2023.06.4
Operating System 10.2
on VM
SmartIR 1.17.7 -> broadlink rm4с mini

**Comment by gavinpbennett** [comment]
+1
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:701
First occurred: 15:39:43 (1 occurrences)
Last logged: 15:39:43

Entity climate.master_bedroom_aircon (<class 'custom_components.smartir.climate.SmartIRClimate'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.

Home Assistant 2023.7.0
Supervisor 2023.07.1
HAOS 10.3
SmartIR 1.17.7 -> broadlink rm4с mini

**Comment by chx0003** [comment]
This issue was already fixed and closed, take a look at https://github.com/smartHomeHub/SmartIR/issues/1048

**Comment by andreamag00** [comment]
I've just saw the old post.. But I still have this warning in my home assistant logs.. Hope they'll fix this in the next update

`Logger: homeassistant.helpers.entity
Source: helpers/entity.py:701 
First occurred: 10:32:48 (2 occurrences) 
Last logged: 10:32:48

Entity climate.ac_app_9_camera_andrea_condizionatore (<class 'custom_components.smartir.climate.SmartIRClimate'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.
Entity climate.ac_app_9_camera_ale_condizionatore (<class 'custom_components.smartir.climate.SmartIRClimate'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.
`

**Comment by Gobolin80** [comment]
+1

Same warning on HA 2023.7.*

`Logger: homeassistant.helpers.entity
Source: helpers/entity.py:701
First occurred: 17:21:35 (4 occurrences)
Last logged: 17:21:41

Entity climate.condizionatore_cucina (<class 'custom_components.smartir.climate.SmartIRClimate'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.
Entity climate.condizionatore_sala (<class 'custom_components.smartir.climate.SmartIRClimate'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.
Entity climate.condizionatore_studio (<class 'custom_components.smartir.climate.SmartIRClimate'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.
Entity climate.condizionatore_camera_da_letto (<class 'custom_components.smartir.climate.SmartIRClimate'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.`
