### ISSUE TITLE
SmartIR Media player homekit broken 

### ISSUE THREAD

**Issue by barns102** [smartHomeHub/SmartIR#206]
**Home Assistant version**

**SmartIR version**

**SmartIR configuration**

```yaml

Add configuration here

```

**Describe the bug

The SmartIR component for media player currently doesn’t work in HomeKit. You have to remove decice_class from customise.ymal just to get all other Home Assistant devices working with HomeKit. SmartIR Climate still works. If you don’t remove the device_type line, then HomeKit won’t connect with HA Bridge. If you do remove everything connects with the exception of the of media player.  I’m assuming this is more of a Apple things rather than an HA or SamrtIR thing. Any advice @smartHomeHub?
**Debug log**

```text

Add your logs here.

```

**Additional context**

**Comment by smartHomeHub** [comment]
Has it worked ok in the past?

**Comment by barns102** [comment]
Yes, absolutely, it worked perfectly. 

Someone has suggested that this might be the solution. 
https://github.com/ikalchev/HAP-python/pull/202

What do you think.

**Comment by smartHomeHub** [comment]
It seems that you have to wait for the fix.

**Comment by jyz0501** [comment]
It is indeed caused by this problem. After testing, it does not have anything to do with Smartir.

**Comment by barns102** [comment]
So how do I fix it?

**Comment by smartHomeHub** [comment]
I merged a PR from @soukron that it seems to solve the problem. Please upgrade.

**Comment by andreskebe** [comment]
I am having the same issue, even if I am running the latest version of SmartIR. 
When I add my 2 media players to my HomeKit config, the home assistant bridge on HomeKit doesn't respond.

**Comment by barns102** [comment]
Im still having the same issue too. Have you ever installed a beta of one of the iOS ‘s lately. This problem accrued for me just after I installed iPadOS beta. It almost feels as if doing that has scared my Apple ID or something. 

I have the latest version of SmartIR, Home Assistant and HomeKit. When I add my media_player to my HomeKit config, the Home Assistant Bridge stops working and the only way to repair it is to remove the media player from the config, remove the bridge and then re-add it. The reason I mention about scaring my Apple ID, is because I can set it up with my partners phone, and everything work, but when I share the home with me, it breaks again. So I’m thinking it’s something to do with my Apple ID as a result of installing iPadOS on one of my devices (which I have now removed, but still doesn’t work). 

Does anyone have any suggestions!!??

**Comment by andreskebe** [comment]
You may be onto something, as I had also just updated my iPad to iPad OS 13.1 yesterday and it was  from yesterday that the media players were not working on home assistant. 
You mentioned removing the beta profile from your iPad, did you also try unenrolling your Apple ID from the beta? From this [link](https://beta.apple.com/sp/betaprogram/login_to_unenroll#macos), there is an option to leave the beta program. 

Hopefully @smartHomeHub can get back to us with a better solution. I will try unenrolling and removing all the beta from the iPad as well.

**Comment by barns102** [comment]
Hey @andreskebe have you had any success?

**Comment by andreskebe** [comment]
I have not.... I removed the beta from my iPad and unenrolled from the beta yet I am having the same issue. 

I then turned on the logs for PyHAP(as per (this)[https://www.home-assistant.io/components/homekit/#troubleshooting] if you're interested) while pairing to see if an exception would be thrown, and no exception was thrown. It seems that according to the logs, the pairing was successful.

**Comment by patrul** [comment]
Any update on this?

Homekit stops working with SmartIR mediaplayer. I have commented media_player on homekit.yaml to continue working with the rest of accesories.

**Comment by andreskebe** [comment]
@smartHomeHub media players are still broken with homekit... it was working super well for me the day before i added my comment. Can we get any updates?
